services:
  train:
    container_name: medium_article_generator_train
    build:
      context: .
      dockerfile: Dockerfile.dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    stdin_open: true
    tty: true

  api:
    container_name: medium_article_generator_api
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
